/**
 * Installable TaskManager (docs/plan/agents.html § S): the install offer, the
 * iOS explainer, the "new version is ready" toast, and the manifest shortcuts'
 * one non-URL intent. The manifest, the icons, the iOS metas and the merged
 * service worker live outside the bundle — static/manifest.webmanifest,
 * static/icons/** (generated by scripts/gen-icons.mjs), src/app.html and
 * src/service-worker.ts.
 */
import { install } from './install.svelte';
import { watchForUpdate } from './update.svelte';

export { install, isIos, isStandalone, dismissed, type InstallKind } from './install.svelte';
export { watchForUpdate } from './update.svelte';
export {
  INTENT,
  NEW_TICKET,
  planIntent,
  withoutIntent,
  openQuickAdd,
  runIntent,
} from './shortcuts';

/**
 * Start the PWA's page-level jobs. Ref-counted on purpose: the account menu is
 * what mounts it (it is on every signed-in screen), and on a phone that menu
 * exists twice — once in the sidebar CSS hides, once in the ☰ drawer.
 */
let mounted = 0;
let stopAll: (() => void) | null = null;

export function startPwa(): () => void {
  if (mounted++ === 0) {
    const offs = [install.start(), watchForUpdate()];
    stopAll = () => offs.forEach((off) => off());
  }
  return () => {
    if (--mounted === 0) {
      stopAll?.();
      stopAll = null;
    }
  };
}
