/**
 * TaskManager inside Claude (docs/plan/agents.html §R3).
 *
 * Two artefacts, both generated by scripts/gen-integration.mjs:
 *
 *   /integrate/claude        the setup page a person reads once — the connector,
 *                            `claude mcp add`, the plugin, and the memory palace
 *   /lib/claude-plugin.zip   the Claude Code plugin: an MCP server, a skill that
 *   /lib/claude-plugin/**    carries the §O context, and five slash commands
 *
 * What can go wrong, and is therefore tested here:
 *
 *   1. They are not served, or served as the wrong thing. A zip handed over as
 *      text is a zip that will not open; a page served as the SPA shell is a
 *      page with nothing on it.
 *   2. The bundle is broken — a zip that will not unpack, a plugin.json Claude
 *      Code cannot read, a command file with no frontmatter. Nobody finds out
 *      until they install it, which is the worst possible moment.
 *   3. It describes an API that no longer exists. The bundle is generated with
 *      the contracts, so the guard that stops a stale /llms-full.txt covers the
 *      plugin too — including the zip, compared byte for byte.
 *
 * The dev stack is vite, so hosting's headers are asserted against firebase.json
 * (the config that produces them), exactly as integration-doc.spec.ts does.
 */
import { spawnSync } from 'node:child_process';
import { mkdtemp, readFile, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { expect, test } from '@playwright/test';
import { MCP_TOOLS } from '@tm/shared';
// @ts-expect-error — plain .mjs shared with the root scripts
import { PLUGIN_FILES, PLUGIN_ZIP, urls } from '../../../scripts/gen-integration.mjs';

const ROOT = new URL('../../../', import.meta.url).pathname;
const STATIC = join(ROOT, 'frontend', 'static');
const U = urls() as { mcpUrl: string; llmsFullUrl: string; claudeUrl: string };

/** The five commands §R3 names, by their file and their slash name. */
const COMMANDS = ['tm-inbox', 'tm-triage', 'tm-new', 'tm-ticket', 'tm-standup'];

test('the Claude guide and every plugin file are served, with the right content type', async ({
  request,
}) => {
  const served = [
    { path: '/integrate/claude/index.html', type: 'text/html', contains: 'TaskManager in Claude' },
    { path: '/lib/claude-plugin/README.md', type: 'markdown', contains: 'Claude Code plugin' },
    {
      path: '/lib/claude-plugin/skills/taskmanager/SKILL.md',
      type: 'markdown',
      contains: 'name: taskmanager',
    },
    {
      path: '/lib/claude-plugin/skills/taskmanager/reference/llms-full.txt',
      type: 'text/plain',
      contains: '# TaskManager — integration context',
    },
    ...COMMANDS.map((c) => ({
      path: `/lib/claude-plugin/commands/${c}.md`,
      type: 'markdown',
      contains: '---',
    })),
  ];
  for (const { path, type, contains } of served) {
    const res = await request.get(path);
    expect(res.status(), `${path} should be served`).toBe(200);
    expect(res.headers()['content-type'], `${path} content-type`).toContain(type);
    expect(await res.text(), `${path} body`).toContain(contains);
  }

  // The bundle itself: a real zip, not an HTML error page with a .zip name.
  const zip = await request.get('/lib/claude-plugin.zip');
  expect(zip.status()).toBe(200);
  expect(zip.headers()['content-type']).toContain('zip');
  const bytes = await zip.body();
  expect(bytes.subarray(0, 4)).toEqual(Buffer.from([0x50, 0x4b, 0x03, 0x04])); // "PK\x03\x04"
  expect(bytes.equals(await readFile(join(STATIC, PLUGIN_ZIP)))).toBe(true);
});

test('the plugin zip unpacks cleanly, into a plugin Claude Code can read', async () => {
  const zip = join(STATIC, PLUGIN_ZIP);

  // `unzip -t` is the real thing reading the archive we hand people, CRCs and
  // all — not our own reader agreeing with our own writer.
  const tested = spawnSync('unzip', ['-t', zip], { encoding: 'utf8' });
  expect(tested.status, tested.stderr || tested.stdout).toBe(0);
  expect(tested.stdout).toContain('No errors detected');

  const dir = await mkdtemp(join(tmpdir(), 'tm-plugin-'));
  const out = spawnSync('unzip', ['-q', zip, '-d', dir], { encoding: 'utf8' });
  expect(out.status, out.stderr || out.stdout).toBe(0);

  // One top-level folder, so `unzip` leaves something you can point Claude at.
  expect(await readdir(dir)).toEqual(['claude-plugin']);
  const root = join(dir, 'claude-plugin');
  const file = (p: string) => readFile(join(root, p), 'utf8');

  // Every file §R3 asks for, including the ones hosting would never serve
  // (the .claude-plugin directory is why the bundle exists).
  for (const f of PLUGIN_FILES as string[]) {
    expect(await file(f), `${f} should be in the bundle`).toBeTruthy();
  }

  const plugin = JSON.parse(await file('.claude-plugin/plugin.json'));
  expect(plugin.name).toBe('taskmanager');
  expect(plugin.mcpServers.taskmanager.type).toBe('http');
  expect(plugin.mcpServers.taskmanager.url).toBe(U.mcpUrl);
  // The token is the user's, never the bundle's: an env reference, not a secret.
  expect(plugin.mcpServers.taskmanager.headers.Authorization).toBe('Bearer ${TM_TOKEN}');
  expect(JSON.stringify(plugin)).not.toContain('tm_live_');

  // The folder is its own marketplace, so `/plugin marketplace add ./claude-plugin` works.
  const market = JSON.parse(await file('.claude-plugin/marketplace.json'));
  expect(market.plugins.map((p: { name: string }) => p.name)).toContain('taskmanager');

  // The skill: frontmatter Claude Code can parse, and the context bundled beside it.
  const skill = await file('skills/taskmanager/SKILL.md');
  expect(skill.startsWith('---\n')).toBe(true);
  const front = skill.slice(4, skill.indexOf('\n---', 4));
  expect(front).toMatch(/^name: taskmanager$/m);
  expect(front).toMatch(/^description: .{40,}$/m);
  expect(skill).toContain('reference/llms-full.txt');
  expect(skill).toContain(U.llmsFullUrl);
  expect(await file('skills/taskmanager/reference/llms-full.txt')).toBe(
    await readFile(join(STATIC, 'llms-full.txt'), 'utf8'),
  );

  // The commands: one file each, with a description the /help list can show.
  for (const c of COMMANDS) {
    const md = await file(`commands/${c}.md`);
    expect(md.startsWith('---\n'), `${c} needs frontmatter`).toBe(true);
    expect(md.slice(0, md.indexOf('\n---', 4)), `${c} needs a description`).toMatch(
      /^description: \S.*$/m,
    );
  }
  // The three that take an argument say so, so `/help` can hint it.
  for (const c of ['tm-triage', 'tm-new', 'tm-ticket']) {
    expect(await file(`commands/${c}.md`), `${c} needs an argument-hint`).toMatch(
      /^argument-hint: /m,
    );
  }
});

test('the skill and the guide describe the API that exists', async ({ request }) => {
  const skill = await (await request.get('/lib/claude-plugin/skills/taskmanager/SKILL.md')).text();
  const page = await (await request.get('/integrate/claude/index.html')).text();

  // The tool table in the skill is generated from the registry — every tool, by name.
  const missing = Object.keys(MCP_TOOLS).filter((name) => !skill.includes(name));
  expect(missing).toEqual([]);

  // §R2: the board argument, and list_boards as the first call, in both.
  for (const text of [skill, page]) {
    expect(text).toContain('list_boards');
    expect(text).toMatch(/board/);
  }

  // §R3: the three routes in, and the memory palace with its one line.
  expect(page).toContain('custom connector');
  expect(page).toContain('claude mcp add --transport http taskmanager');
  expect(page).toContain('--scope user');
  expect(page).toContain('/mcp');
  expect(page).toContain('claude-plugin.zip');
  expect(page).toContain('/plugin marketplace add');
  expect(page).toContain('--plugin-dir');
  for (const c of COMMANDS) expect(page).toContain(`/${c}`);
  expect(page).toContain('memory palace');
  expect(page).toContain(`Read ${U.llmsFullUrl} first.`);
});

test('llms-full.txt tells an agent about account tokens and the board argument', async ({
  request,
}) => {
  const text = await (await request.get('/llms-full.txt')).text();
  expect(text).toContain('account token');
  expect(text).toContain('list_boards');
  expect(text).toMatch(/`board` argument/);
  // The Claude page and the plugin are discoverable from the context itself.
  expect(text).toContain(U.claudeUrl);
  const manifest = await (await request.get('/integrate.json')).json();
  expect(manifest.claude.guideUrl).toBe(U.claudeUrl);
  expect(manifest.claude.mcpAddCommand).toContain('claude mcp add --transport http taskmanager');
});

test('the /lib index and the integration page point at the Claude guide', async ({ request }) => {
  const lib = await (await request.get('/lib/index.html')).text();
  expect(lib).toContain('/integrate/claude');
  expect(lib).toContain('/lib/claude-plugin.zip');
  const integrate = await (await request.get('/integrate/index.html')).text();
  expect(integrate).toContain('/integrate/claude');
});

test('hosting serves the guide and the bundle with the right types and no stale caching', async () => {
  const cfg = JSON.parse(await readFile(join(ROOT, 'firebase.json'), 'utf8'));
  const headers: { source: string; headers: { key: string; value: string }[] }[] =
    cfg.hosting.headers;
  const valueFor = (source: string, key: string) =>
    headers
      .filter((h) => h.source === source)
      .flatMap((h) => h.headers)
      .find((h) => h.key.toLowerCase() === key)?.value;

  expect(valueFor('/lib/**/*.zip', 'content-type')).toBe('application/zip');
  expect(valueFor('/lib/**/*.md', 'content-type')).toContain('text/markdown');
  // The bundle carries the whole context, so a cached copy is a stale context.
  expect(valueFor('/lib/claude-plugin.zip', 'cache-control')).toBe('no-cache');
  expect(valueFor('/lib/claude-plugin/**', 'cache-control')).toBe('no-cache');
  // All three spellings of the guide, the way /integrate already does it.
  for (const source of [
    '/integrate/claude',
    '/integrate/claude/',
    '/integrate/claude/index.html',
  ]) {
    expect(valueFor(source, 'cache-control'), source).toBe('no-cache');
    expect(valueFor(source, 'access-control-allow-origin'), source).toBe('*');
  }
  // A blanket '**/.*' would drop .claude-plugin/plugin.json from the deploy.
  expect(cfg.hosting.ignore).not.toContain('**/.*');

  // The production deploy uses firebase.deploy.json; the headers must survive it.
  const deployCfg = JSON.parse(await readFile(join(ROOT, 'firebase.deploy.json'), 'utf8'));
  expect(deployCfg.hosting.headers).toEqual(cfg.hosting.headers);
  expect(deployCfg.hosting.ignore).toEqual(cfg.hosting.ignore);
});
