/**
 * indicators.html — INDICATOR_ICONS id → its lucide component. A STATIC map
 * (tree-shaken to exactly these icons); never a dynamic import by name.
 */
import type { IndicatorIcon } from '@tm/shared';
import {
  LayoutGrid as LayoutGridIcon,
  Kanban as KanbanIcon,
  ListTodo as ListTodoIcon,
  SquareCheck as SquareCheckIcon,
  CircleDot as CircleDotIcon,
  Target as TargetIcon,
  Flag as FlagIcon,
  Rocket as RocketIcon,
  Zap as ZapIcon,
  Star as StarIcon,
  Heart as HeartIcon,
  Bookmark as BookmarkIcon,
  Tag as TagIcon,
  Bell as BellIcon,
  Calendar as CalendarIcon,
  Clock as ClockIcon,
  Briefcase as BriefcaseIcon,
  Building2 as Building2Icon,
  House as HouseIcon,
  Users as UsersIcon,
  User as UserIcon,
  GraduationCap as GraduationCapIcon,
  BookOpen as BookOpenIcon,
  NotebookPen as NotebookPenIcon,
  FileText as FileTextIcon,
  Folder as FolderIcon,
  Archive as ArchiveIcon,
  Inbox as InboxIcon,
  Mail as MailIcon,
  MessageSquare as MessageSquareIcon,
  Phone as PhoneIcon,
  Camera as CameraIcon,
  Image as ImageIcon,
  Film as FilmIcon,
  Music as MusicIcon,
  Mic as MicIcon,
  Headphones as HeadphonesIcon,
  Palette as PaletteIcon,
  Brush as BrushIcon,
  PenTool as PenToolIcon,
  Code as CodeIcon,
  Terminal as TerminalIcon,
  Bug as BugIcon,
  GitBranch as GitBranchIcon,
  Database as DatabaseIcon,
  Server as ServerIcon,
  Cloud as CloudIcon,
  Cpu as CpuIcon,
  Smartphone as SmartphoneIcon,
  Monitor as MonitorIcon,
  Globe as GlobeIcon,
  Map as MapIcon,
  Compass as CompassIcon,
  Plane as PlaneIcon,
  Car as CarIcon,
  Bike as BikeIcon,
  ShoppingCart as ShoppingCartIcon,
  CreditCard as CreditCardIcon,
  Wallet as WalletIcon,
  PiggyBank as PiggyBankIcon,
  ChartLine as ChartLineIcon,
  ChartPie as ChartPieIcon,
  TrendingUp as TrendingUpIcon,
  Dumbbell as DumbbellIcon,
  Activity as ActivityIcon,
  Apple as AppleIcon,
  Coffee as CoffeeIcon,
  Utensils as UtensilsIcon,
  Leaf as LeafIcon,
  Sun as SunIcon,
  Moon as MoonIcon,
  Flame as FlameIcon,
  Gift as GiftIcon,
  Trophy as TrophyIcon,
  Shield as ShieldIcon,
  Lock as LockIcon,
  Key as KeyIcon,
  Wrench as WrenchIcon,
  Hammer as HammerIcon,
  Lightbulb as LightbulbIcon,
  Brain as BrainIcon,
  Sparkles as SparklesIcon,
  Bot as BotIcon,
  Gamepad2 as Gamepad2Icon,
  Puzzle as PuzzleIcon,
  Box as BoxIcon,
  Package as PackageIcon,
} from 'lucide-svelte';
import type { IconComponent } from './types';

export const INDICATOR_ICON_COMPONENTS: Record<IndicatorIcon, IconComponent> = {
  'layout-grid': LayoutGridIcon,
  'kanban': KanbanIcon,
  'list-todo': ListTodoIcon,
  'check-square': SquareCheckIcon,
  'circle-dot': CircleDotIcon,
  'target': TargetIcon,
  'flag': FlagIcon,
  'rocket': RocketIcon,
  'zap': ZapIcon,
  'star': StarIcon,
  'heart': HeartIcon,
  'bookmark': BookmarkIcon,
  'tag': TagIcon,
  'bell': BellIcon,
  'calendar': CalendarIcon,
  'clock': ClockIcon,
  'briefcase': BriefcaseIcon,
  'building-2': Building2Icon,
  'home': HouseIcon,
  'users': UsersIcon,
  'user': UserIcon,
  'graduation-cap': GraduationCapIcon,
  'book-open': BookOpenIcon,
  'notebook-pen': NotebookPenIcon,
  'file-text': FileTextIcon,
  'folder': FolderIcon,
  'archive': ArchiveIcon,
  'inbox': InboxIcon,
  'mail': MailIcon,
  'message-square': MessageSquareIcon,
  'phone': PhoneIcon,
  'camera': CameraIcon,
  'image': ImageIcon,
  'film': FilmIcon,
  'music': MusicIcon,
  'mic': MicIcon,
  'headphones': HeadphonesIcon,
  'palette': PaletteIcon,
  'brush': BrushIcon,
  'pen-tool': PenToolIcon,
  'code': CodeIcon,
  'terminal': TerminalIcon,
  'bug': BugIcon,
  'git-branch': GitBranchIcon,
  'database': DatabaseIcon,
  'server': ServerIcon,
  'cloud': CloudIcon,
  'cpu': CpuIcon,
  'smartphone': SmartphoneIcon,
  'monitor': MonitorIcon,
  'globe': GlobeIcon,
  'map': MapIcon,
  'compass': CompassIcon,
  'plane': PlaneIcon,
  'car': CarIcon,
  'bike': BikeIcon,
  'shopping-cart': ShoppingCartIcon,
  'credit-card': CreditCardIcon,
  'wallet': WalletIcon,
  'piggy-bank': PiggyBankIcon,
  'chart-line': ChartLineIcon,
  'chart-pie': ChartPieIcon,
  'trending-up': TrendingUpIcon,
  'dumbbell': DumbbellIcon,
  'activity': ActivityIcon,
  'apple': AppleIcon,
  'coffee': CoffeeIcon,
  'utensils': UtensilsIcon,
  'leaf': LeafIcon,
  'sun': SunIcon,
  'moon': MoonIcon,
  'flame': FlameIcon,
  'gift': GiftIcon,
  'trophy': TrophyIcon,
  'shield': ShieldIcon,
  'lock': LockIcon,
  'key': KeyIcon,
  'wrench': WrenchIcon,
  'hammer': HammerIcon,
  'lightbulb': LightbulbIcon,
  'brain': BrainIcon,
  'sparkles': SparklesIcon,
  'bot': BotIcon,
  'gamepad-2': Gamepad2Icon,
  'puzzle': PuzzleIcon,
  'box': BoxIcon,
  'package': PackageIcon,
};

/** 'chart-line' → 'Chart line' (tooltips, aria labels, the icon grid search). */
export function iconLabel(id: string): string {
  const s = id.replace(/-\d+$/, '').replace(/-/g, ' ');
  return s.charAt(0).toUpperCase() + s.slice(1);
}
