// dist/index.html → backend/src/doors/mcpUiHtml.gen.ts (see vite.config.ts).
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(here, 'dist/index.html'), 'utf8');
const out = join(here, '../../backend/src/doors/mcpUiHtml.gen.ts');
writeFileSync(
  out,
  '/** GENERATED by frontend/mcp-ui (pnpm --filter ./frontend mcp-ui:build) — do not edit. */\n' +
    `export const MCP_UI_HTML = ${JSON.stringify(html)};\n`,
);
console.log(`mcp-ui: ${(html.length / 1024).toFixed(1)} KiB → ${out}`);
