/**
 * One valid sample per stored entity — for tests, emulator seeds and
 * converters. Import from '@tm/shared/schema/fixtures' (kept out of the main
 * barrel so app bundles do not carry it). Every sample must parse with its
 * schema in DOC_SCHEMAS; the fixture test enforces that.
 */
import { defaultChannelMatrix, type RichText } from '../types/index.js';
import type { DocName, DocOf } from './index.js';

export const T0 = Date.UTC(2026, 8, 22, 9, 0, 0); // 2026-09-22 09:00 UTC

export const UID_ASHA = 'uid_asha';
export const UID_PRIYA = 'uid_priya';
export const BOARD_ID = 'board_eng';
export const TICKET_ID = 'tkt_0001';
/** Phase 2: an agent owned by Asha. */
export const AGENT_ID = 'ag_Bu1lder000000001';

export const sampleRichText: RichText = {
  doc: {
    type: 'doc',
    content: [
      {
        type: 'paragraph',
        content: [
          { type: 'text', text: 'Ping ' },
          { type: 'mention', attrs: { uid: UID_PRIYA } },
          { type: 'text', text: ' about ' },
          { type: 'ticketRef', attrs: { ticketId: 'tkt_0002', key: 'ENG-2' } },
        ],
      },
    ],
  },
  text: 'Ping @Priya Shah about #ENG-2',
  mentions: [UID_PRIYA],
  refs: ['tkt_0002'],
};

export const fixtures: { [N in DocName]: DocOf<N> } = {
  users: {
    name: 'Asha Rao',
    email: 'asha@example.com',
    avatarPath: `users/${UID_ASHA}/avatar/${T0}.webp`,
    timezone: 'Asia/Kolkata',
    locale: 'en-IN',
    theme: 'system',
    whatsapp: null,
    notify: {
      channels: defaultChannelMatrix(),
      quietHours: { start: '22:00', end: '08:00' },
      digest: 'off',
      dueSoonLeadMinutes: 1440,
      commitmentReminders: true,
    },
    createdAt: T0,
    deletedAt: null,
  },
  devices: { fcmToken: 'fcm-token-abc', kind: 'web', userAgent: 'Mozilla/5.0', lastSeenAt: T0 },
  inbox: {
    event: 'comment',
    boardId: BOARD_ID,
    ticketId: TICKET_ID,
    ticketKey: 'ENG-1',
    ticketTitle: 'Fix login redirect',
    inviteId: null,
    actor: UID_PRIYA,
    via: 'app',
    summary: 'commented: looks good',
    messageId: 'msg_1',
    groupKey: `${TICKET_ID}:comment`,
    count: 1,
    createdAt: T0,
    readAt: null,
    archivedAt: null,
    snoozedUntil: null,
  },
  reads: { boardId: BOARD_ID, readAt: T0 },
  invites: {
    boardId: BOARD_ID,
    boardName: 'Engineering',
    boardKey: 'ENG',
    email: 'newbie@example.com',
    role: 'editor',
    invitedBy: UID_ASHA,
    invitedByName: 'Asha Rao',
    message: null,
    tokenHash: 'e3b0c44298fc1c149afbf4c8996fb924',
    status: 'pending',
    expiresAt: T0 + 14 * 86_400_000,
    createdAt: T0,
  },
  boardKeys: { boardId: BOARD_ID, claimedAt: T0 },
  boards: {
    name: 'Engineering',
    key: 'ENG',
    nextNumber: 2,
    color: '#2f6fed',
    icon: 'code',
    description: null,
    access: { [UID_ASHA]: 'admin', [UID_PRIYA]: 'commenter' },
    stageGrants: { [UID_PRIYA]: { stages: ['st_rev', 'st_done'], assignedOnly: true } },
    readerUids: [UID_ASHA, UID_PRIYA],
    editorUids: [UID_ASHA],
    stages: [
      { id: 'st_todo', name: 'To do', color: '#888', category: 'todo', position: 0 },
      {
        id: 'st_rev',
        name: 'In review',
        color: '#fa0',
        category: 'active',
        position: 1,
        wipLimit: 5,
      },
      {
        id: 'st_done',
        name: 'Done',
        color: '#0a0',
        category: 'done',
        position: 2,
        requires: ['f_soluti'],
      },
    ],
    priorities: [{ id: 'p_high', name: 'High', color: '#f00', position: 0 }],
    tags: [{ id: 'tg_bug', name: 'bug', position: 0 }],
    fields: [
      { id: 'f_soluti', name: 'Solution', type: 'longText', position: 0 },
      {
        id: 'f_client',
        name: 'Client',
        type: 'select',
        options: [{ id: 'o_acme', name: 'Acme', position: 0 }],
        position: 1,
        showOnCard: true,
      },
    ],
    defaultViewId: 'v_board',
    settings: { allowDelete: false, emailReplies: true, autoArchiveDoneAfterDays: null },
    counts: { active: 1, done: 0, overdue: 0 },
    archivedAt: null,
    createdBy: UID_ASHA,
    createdAt: T0,
  },
  members: {
    kind: 'user',
    uid: UID_PRIYA,
    role: 'commenter',
    stageGrant: { stages: ['st_rev', 'st_done'] },
    name: 'Priya Shah',
    email: 'priya@example.com',
    avatarPath: null,
    invitedBy: UID_ASHA,
    joinedAt: T0,
  },
  prefs: {
    mode: 'mine',
    events: ['assigned', 'mentioned'],
    watching: [TICKET_ID],
    starred: true,
    lastViewId: 'v_board',
  },
  views: {
    name: 'Mine, due this week',
    type: 'kanban',
    scope: 'personal',
    ownerUid: UID_ASHA,
    position: 3,
    filter: {
      op: 'and',
      children: [
        { field: 'assignee', cmp: 'is', value: 'me' },
        { field: 'due', cmp: 'before', value: 'thisWeek' },
        { field: 'fields.f_client', cmp: 'in', value: ['o_acme'] },
      ],
    },
    sort: [{ field: 'due', dir: 'asc' }],
    groupBy: 'stage',
    subGroupBy: null,
    columns: [{ field: 'title', width: 320 }],
    dateField: 'due',
    endDateField: null,
    cardFields: ['priority', 'assignee'],
    includeStates: ['active'],
  },
  tickets: {
    key: 'ENG-1',
    number: 1,
    title: 'Fix login redirect',
    description: sampleRichText,
    stageId: 'st_todo',
    stageCategory: 'todo',
    priorityId: 'p_high',
    tagIds: ['tg_bug'],
    state: 'active',
    rank: 'a0',
    assigneeUids: [UID_PRIYA],
    watcherUids: [UID_ASHA, UID_PRIYA],
    reporter: { uid: UID_ASHA, name: 'Asha Rao' },
    startAt: null,
    dueAt: T0 + 86_400_000,
    dueAllDay: true,
    commitments: { [UID_PRIYA]: T0 + 3_600_000 },
    estimate: 3,
    fields: { f_client: 'o_acme', f_soluti: null },
    refs: ['tkt_0002'],
    referencedBy: [],
    links: [{ type: 'blocks', ticketId: 'tkt_0002' }],
    counts: { messages: 1, files: 0, pinned: 0 },
    lastMessageAt: T0,
    lastActivityAt: T0,
    dueNotified: { [UID_PRIYA]: { soon: T0 } },
    createdBy: UID_ASHA,
    createdVia: 'app',
    createdAt: T0,
    updatedAt: T0,
    completedAt: null,
    // phase 15 (§W): the thread lives on the ticket
    signals: {
      messageCount: 1,
      lastMessageAt: T0,
      lastActivityAt: T0,
      unreadFrom: T0,
      question: null,
      tasklist: { done: 1, total: 3, working: 'Write the migration' },
      fileCount: 1,
      blocked: false,
    },
    tasklists: [],
    files: [],
    fileIds: ['att_1'],
    recentMessages: [],
    recentActivity: [],
    pageCount: 0,
    oldestInlineAt: T0,
    nextQuestionExpiresAt: null,
  },
  messages: {
    kind: 'comment',
    body: sampleRichText,
    authorUid: UID_ASHA,
    authorName: 'Asha Rao',
    via: 'app',
    replyTo: null,
    attachments: [
      {
        id: 'att_1',
        path: `boards/${BOARD_ID}/tickets/${TICKET_ID}/att_1/screenshot.png`,
        name: 'screenshot.png',
        mime: 'image/png',
        size: 12345,
        width: 800,
        height: 600,
        uploadedBy: UID_ASHA,
      },
    ],
    reactions: { '👍': [UID_PRIYA] },
    pinnedAt: null,
    pinnedBy: null,
    editedAt: null,
    deletedAt: null,
    createdAt: T0,
  },
  activity: {
    action: 'update',
    changes: { stageId: { from: 'st_todo', to: 'st_rev' } },
    actor: UID_PRIYA,
    via: 'app',
    viaGrant: ['st_rev', 'st_done'],
    createdAt: T0,
  },
  files: {
    id: 'att_1',
    path: `boards/${BOARD_ID}/tickets/${TICKET_ID}/att_1/screenshot.png`,
    name: 'screenshot.png',
    mime: 'image/png',
    size: 12345,
    uploadedBy: UID_ASHA,
    source: 'message',
    messageId: 'msg_1',
    createdAt: T0,
    deletedAt: null,
  },
  ticketData: {
    page: 0,
    messages: [],
    activity: [],
    from: T0,
    to: T0,
    createdAt: T0,
  },
  stats: {
    day: '2026-09-26',
    costUsd: 1.24,
    runs: 1,
    tickets: { 'ENG-1': { usd: 1.24, runs: 1 } },
    updatedAt: T0,
  },
  keys: { ticketId: TICKET_ID, boardId: BOARD_ID, current: 'ENG-1' },
  presence: { state: 'online', viewing: TICKET_ID, lastChanged: T0 },
  typing: { at: T0 },
  'tickets index': {
    id: TICKET_ID,
    boardId: BOARD_ID,
    key: 'ENG-1',
    title: 'Fix login redirect',
    text: 'Ping @Priya Shah about #ENG-2',
    stageCategory: 'todo',
    assigneeUids: [UID_PRIYA],
    state: 'active',
    updatedAt: T0,
  },
  apiKeys: {
    name: 'orch-eng-builder',
    kind: 'board',
    boardId: BOARD_ID,
    actsAs: { kind: 'agent', id: AGENT_ID },
    prefix: 'tm_live_3fa9',
    hash: 'abc123',
    scopes: [
      'board:read',
      'tickets:read',
      'comments:read',
      'comments:write',
      'files:read',
      'files:write',
      'tickets:move',
      'events:read',
    ],
    limits: { perMin: 60, perDay: 10000 },
    lastUsedAt: null,
    expiresAt: null,
    revokedAt: null,
    createdAt: T0,
  },
  oauthClients: {
    name: 'Claude',
    redirectUris: ['https://claude.ai/api/mcp/auth_callback'],
    public: true,
    registeredVia: 'dcr',
    createdAt: T0,
  },
  oauthGrants: {
    clientId: 'client_1',
    clientName: 'Claude',
    scopes: ['board:read', 'tickets:read', 'tickets:update', 'comments:write'],
    createdAt: T0,
    lastUsedAt: T0,
  },
  oauthTokens: {
    kind: 'code',
    uid: UID_ASHA,
    grantId: 'grant_1',
    clientId: 'client_1',
    scopes: ['tickets:read'],
    codeChallenge: 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM',
    expiresAt: T0 + 60_000,
  },
  webhooks: {
    url: 'https://hooks.example.com/tm',
    secretHash: 'deadbeef',
    events: ['ticket.created', 'ticket.moved'],
    active: true,
    failures: 0,
    createdBy: UID_ASHA,
    createdAt: T0,
  },
  webhookDeliveries: {
    event: 'ticket.moved',
    envelopeId: 'evt_1',
    attempt: 1,
    status: 'failed',
    responseCode: 500,
    responseSnippet: 'Internal Server Error',
    durationMs: 120,
    nextAttemptAt: T0 + 60_000,
    createdAt: T0,
  },
  installs: {
    provider: 'github',
    status: 'active',
    externalId: '12345',
    config: { repos: [{ fullName: 'acme/web', moveOnMerge: 'st_done' }] },
    connectedBy: UID_ASHA,
    connectedAt: T0,
  },
  intakes: {
    boardId: BOARD_ID,
    enabled: true,
    secretHash: 'cafebabe',
    rotatedAt: T0,
    limits: { perMin: 10, perHour: 100, perDay: 500 },
    allowedOrigins: ['https://acme.example.com'],
    defaults: { stageId: 'st_todo', tagIds: ['tg_bug'] },
    fieldMap: { client: 'f_client' },
    email: 'eng-bugs@in.taskmanager.app',
  },
  deliveries: {
    uid: UID_PRIYA,
    channel: 'email',
    groupKey: `${TICKET_ID}:comment`,
    inboxIds: ['n_1'],
    status: 'sent',
    provider: 'resend',
    providerId: 're_123',
    error: null,
    createdAt: T0,
  },
  emailThreads: {
    boardId: BOARD_ID,
    ticketId: TICKET_ID,
    uid: UID_PRIYA,
    messageIdHeader: '<ticket-tkt_0001@taskmanager.app>',
    expiresAt: T0 + 90 * 86_400_000,
  },
  whatsappSessions: {
    uid: UID_PRIYA,
    lastInboundAt: T0,
    contextTicketId: TICKET_ID,
    contextExpiresAt: T0 + 86_400_000,
  },
  agents: {
    ownerUid: UID_ASHA,
    name: 'Builder',
    avatarPath: `users/${UID_ASHA}/agents/${AGENT_ID}/avatar/1758531600000.webp`,
    systemPrompt: '# Builder\n\nYou implement tickets assigned to you and report back in Markdown.',
    description: 'Implements engineering tickets',
    createdAt: T0,
    updatedAt: T0,
    archivedAt: null,
  },
  agentInbox: {
    type: 'assigned',
    boardId: BOARD_ID,
    ticketId: TICKET_ID,
    ticketKey: 'ENG-1',
    messageId: null,
    actor: UID_ASHA,
    summary: 'Asha Rao assigned you ENG-1',
    createdAt: T0,
    ackedAt: null,
  },
  // phase 3 (agents.html §L)
  tasklists: {
    title: 'Plan: add CSV export',
    owner: AGENT_ID,
    items: [
      { id: 'it_1', title: 'Read the ticket and the linked docs', status: 'done', updatedAt: T0 },
      { id: 'it_2', title: 'Write the exporter', status: 'doing', updatedAt: T0 + 60_000 },
      { id: 'it_3', title: 'Add tests', status: 'todo', updatedAt: T0 },
    ],
    position: 0,
    createdAt: T0,
    updatedAt: T0 + 60_000,
    closedAt: null,
  },
  agentStatus: {
    agentId: AGENT_ID,
    ticketId: TICKET_ID,
    state: 'working',
    message: 'Running tests (3/12)',
    progress: 0.25,
    lastBeatAt: T0 + 60_000,
    startedAt: T0,
    endedAt: null,
    silenceNotifiedAt: null,
  },
  artifacts: {
    name: 'Sales dashboard',
    description: 'Weekly numbers, straight from the sheet.',
    icon: null,
    ownerUid: UID_ASHA,
    access: { [UID_ASHA]: 'owner', [UID_PRIYA]: 'viewer' },
    memberUids: [UID_ASHA, UID_PRIYA],
    agents: { [AGENT_ID]: { build: true, data: 'write' } },
    readOnly: false,
    archivedAt: null,
    currentBuild: 'build_0000000001',
    createdAt: T0,
    updatedAt: T0 + 60_000,
  },
  artifactBuilds: {
    files: 7,
    bytes: 184_320,
    message: 'first cut',
    sourcePath: 'artifacts/art_0000000001/source/build_0000000001.zip',
    by: AGENT_ID,
    createdAt: T0 + 60_000,
    warnings: [],
  },
  artifactKv: { value: { theme: 'dark' }, updatedAt: T0 },
  workspaces: {
    name: 'Freelance',
    color: '#6366F1',
    boardIds: [BOARD_ID],
    artifactIds: ['art_dash'],
    position: 0,
    createdAt: T0,
    updatedAt: T0,
  },
  sidebarPrefs: { hiddenBoardIds: [BOARD_ID], hiddenArtifactIds: [], updatedAt: T0 },
  memories: {
    name: 'Brand kit',
    description: 'Logos, screenshots and the style guide',
    icon: null,
    ownerUid: UID_ASHA,
    access: { [UID_ASHA]: 'owner' },
    memberUids: [UID_ASHA],
    boards: { [BOARD_ID]: 'read' },
    artifacts: {},
    boardIds: [BOARD_ID],
    stats: { files: 1, folders: 1, bytes: 2048 },
    archivedAt: null,
    createdAt: T0,
    updatedAt: T0,
  },
  memoryNodes: {
    kind: 'file',
    parentId: 'node_folder1',
    name: 'logo.svg',
    path: 'logos/logo.svg',
    file: {
      fileId: 'file_abc123',
      storagePath: 'memories/memory_brand1/file_abc123/logo.svg',
      mime: 'image/svg+xml',
      size: 2048,
    },
    createdAt: T0,
    createdBy: UID_ASHA,
    updatedAt: T0,
    updatedBy: UID_ASHA,
  },
};

/** Phase 3: the question card in the thread (a message with kind 'question'). */
export const questionMessageFixture: DocOf<'messages'> = {
  ...fixtures.messages,
  kind: 'question',
  authorUid: AGENT_ID,
  authorName: 'Builder',
  via: 'api',
  viaToken: 'orch-eng-builder',
  question: {
    title: 'Which database should the report use?',
    body: null,
    fields: [
      {
        id: 'f_db',
        label: 'Database',
        type: 'single',
        required: true,
        options: [
          { id: 'o_pg', label: 'Postgres', description: 'The reporting replica' },
          { id: 'o_bq', label: 'BigQuery' },
        ],
      },
      { id: 'f_note', label: 'Anything to watch out for?', type: 'text', placeholder: 'Optional' },
    ],
    allowComment: true,
    to: [UID_ASHA],
    blocking: true,
    status: 'open',
    expiresAt: null,
    answer: null,
    cancelledAt: null,
  },
};

/** Phase 2: the agent's row on the board (members/{AGENT_ID}). */
export const agentMemberFixture: DocOf<'members'> = {
  kind: 'agent',
  uid: AGENT_ID,
  role: 'commenter',
  stageGrant: { stages: ['st_rev', 'st_done'] },
  name: 'Builder',
  email: '',
  avatarPath: null,
  invitedBy: null,
  ownerUid: UID_ASHA,
  addedBy: UID_ASHA,
  description: 'Implements engineering tickets',
  joinedAt: T0,
};

/** One clearly-invalid sample per entity (a required field missing or mistyped). */
export const invalidFixtures: { [N in DocName]: unknown } = {
  users: { ...fixtures.users, theme: 'purple' },
  devices: { ...fixtures.devices, kind: 'fridge' },
  inbox: { ...fixtures.inbox, event: 'poked' },
  reads: { boardId: BOARD_ID },
  invites: { ...fixtures.invites, email: 'Upper@Example.com' },
  boardKeys: { claimedAt: T0 },
  boards: { ...fixtures.boards, key: 'engineering' },
  members: { ...fixtures.members, role: 'owner' },
  prefs: { ...fixtures.prefs, mode: 'loud' },
  views: { ...fixtures.views, type: 'gallery' },
  tickets: { ...fixtures.tickets, key: 'eng-1' },
  messages: { ...fixtures.messages, kind: 'reply' },
  activity: { ...fixtures.activity, action: 'teleport' },
  files: { ...fixtures.files, source: 'email' },
  ticketData: { ...fixtures.ticketData, page: -1 },
  stats: { ...fixtures.stats, day: '26/09/2026' },
  keys: { ...fixtures.keys, current: 'ENG' },
  presence: { ...fixtures.presence, state: 'busy' },
  typing: { at: 'now' },
  'tickets index': { ...fixtures['tickets index'], state: 'open' },
  apiKeys: { ...fixtures.apiKeys, scopes: ['everything'] },
  oauthClients: { ...fixtures.oauthClients, registeredVia: 'email' },
  oauthGrants: { ...fixtures.oauthGrants, clientId: '' },
  oauthTokens: { ...fixtures.oauthTokens, kind: 'id' },
  webhooks: { ...fixtures.webhooks, url: 'http://insecure.example.com' },
  webhookDeliveries: { ...fixtures.webhookDeliveries, status: 'maybe' },
  installs: { ...fixtures.installs, provider: 'jira' },
  intakes: { ...fixtures.intakes, enabled: 'yes' },
  deliveries: { ...fixtures.deliveries, channel: 'fax' },
  emailThreads: { ...fixtures.emailThreads, ticketId: undefined },
  whatsappSessions: { ...fixtures.whatsappSessions, uid: '' },
  agents: { ...fixtures.agents, name: '' },
  agentInbox: { ...fixtures.agentInbox, type: 'poked' },
  tasklists: {
    ...fixtures.tasklists,
    items: [{ id: 'it_1', title: 'x', status: 'blocked', updatedAt: T0 }],
  },
  agentStatus: { ...fixtures.agentStatus, state: 'thinking' },
  artifacts: { ...fixtures.artifacts, access: { [UID_ASHA]: 'admin' } },
  artifactBuilds: { ...fixtures.artifactBuilds, files: -1 },
  artifactKv: { value: 1 },
  workspaces: { ...fixtures.workspaces, color: 'indigo' },
  sidebarPrefs: { hiddenBoardIds: 'board_eng', hiddenArtifactIds: [], updatedAt: T0 },
  memories: { ...fixtures.memories, boards: { [BOARD_ID]: 'admin' } },
  memoryNodes: { ...fixtures.memoryNodes, path: '/abs/path' },
};
