/**
 * Build window.BackendDriver and STAGE it where hosting serves it
 * (docs/plan/artifacts.html §E1):
 *
 *   src/iife.ts  ──esbuild (iife, minified)──▶  driver.js    <script src>; sets window.BackendDriver
 *   src/index.ts ──esbuild (esm,  minified)──▶  driver.mjs   import db from '…/driver.mjs'
 *   src/api.ts   ──+ the value declarations──▶  driver.d.ts  one flat file, no imports
 *
 * …into frontend/static/backend-driver/v1/ AND …/latest/ — the same bytes
 * twice, as /lib does: v1 is what an artifact pins (hosting caches it for a
 * year, so it must never change shape under them), latest is the moving one.
 * frontend/static/backend-driver/index.html (the usage page) is a plain file
 * and is left alone.
 *
 * WHY STAGE INTO static/ AND COMMIT IT. Unlike the SDK (megabytes, staged into
 * build/ at deploy time), this is a few kilobytes that `vite dev` must serve
 * too: an artifact under development loads the driver from the dev server.
 * A committed copy means a fresh checkout works before anything is built, and
 * the frontend build re-runs this (vite.config.ts) so it cannot go stale.
 *
 * The protocol (@tm/shared/artifacts/driver) and the path fence
 * (@tm/shared/artifacts/paths) are BUNDLED IN from their TypeScript source:
 * the output has no imports, and neither file pulls in zod.
 *
 *   node build.mjs [--quiet] [--check]
 *
 *   --check   build to a temp dir and fail if the staged files differ (CI)
 */
import { createRequire } from 'node:module';
import { spawnSync } from 'node:child_process';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const tmp = join(here, '.tmp');
const STATIC = join(here, '..', 'frontend', 'static', 'backend-driver');
/** `v1` is the wire version (DRIVER_PROTOCOL_VERSION), not the package version. */
const CHANNELS = ['v1', 'latest'];
const FILES = ['driver.js', 'driver.mjs', 'driver.d.ts'];
/**
 * "A few kilobytes of postMessage plumbing" — the mock is most of it. Shout if it balloons.
 * 24 KB → 28 KB with memory.html §H (db.memory and the mock's demo memory, ~2 KB).
 * 28 KB → 34 KB with §K reads (tickets.thread / aggregates and the mock's
 * sample thread and buckets, ~5.5 KB).
 */
const MAX_BYTES = 34 * 1024;

const args = new Set(process.argv.slice(2));
const quiet = args.has('--quiet');
const log = (...m) => quiet || console.log(...m);

/** Everything an artifact's TypeScript needs, after the types of src/api.ts. */
const DTS_FOOTER = `
/** The one driver of this window. */
export declare const BackendDriver: BackendDriver;
export default BackendDriver;

declare global {
  interface Window {
    BackendDriver: BackendDriver;
  }
}
`;

function tsc(argv) {
  const bin = join(dirname(require.resolve('typescript/package.json')), 'bin', 'tsc');
  const r = spawnSync(process.execPath, [bin, ...argv], { encoding: 'utf8' });
  if (r.status !== 0) throw new Error(`tsc ${argv.join(' ')}\n${r.stdout}${r.stderr}`);
}

async function build(out) {
  const { version } = JSON.parse(await readFile(join(here, 'package.json'), 'utf8'));
  await rm(tmp, { recursive: true, force: true });
  await mkdir(tmp, { recursive: true });
  await mkdir(out, { recursive: true });

  const esbuild = await import('esbuild');
  // The staged files sit under frontend/static, which the repo's eslint walks.
  const banner = `/* eslint-disable */\n//! @tm/backend-driver ${version} — generated by driver/build.mjs, do not edit`;
  const common = {
    bundle: true,
    minify: true,
    target: 'es2020',
    platform: 'browser',
    // @tm/shared → its TypeScript source, so a stale shared/dist can never be bundled.
    conditions: ['@tm/source'],
    legalComments: 'none',
    absWorkingDir: here,
  };
  await esbuild.build({
    ...common,
    entryPoints: ['src/iife.ts'],
    format: 'iife',
    banner: { js: banner },
    outfile: join(out, 'driver.js'),
  });
  await esbuild.build({
    ...common,
    entryPoints: ['src/index.ts'],
    format: 'esm',
    // Deno and Bun read the triple-slash reference for types.
    banner: { js: `/// <reference types="./driver.d.ts" />\n${banner}` },
    outfile: join(out, 'driver.mjs'),
  });

  // The declaration file: api.ts as it is (types only, no imports) + the values.
  const api = await readFile(join(here, 'src', 'api.ts'), 'utf8');
  if (/^\s*import\s/m.test(api))
    throw new Error('src/api.ts must have no imports — it ships as driver.d.ts');
  const dts = `// @tm/backend-driver ${version} — generated by driver/build.mjs from driver/src/api.ts, do not edit.\n${api}${DTS_FOOTER}`;
  await writeFile(join(out, 'driver.d.ts'), dts);

  await smoke(out, version);
  await rm(tmp, { recursive: true, force: true });
}

/** Look at each artefact before it ships, so a broken build never reaches static/. */
async function smoke(out, version) {
  for (const f of ['driver.js', 'driver.mjs']) {
    const src = await readFile(join(out, f), 'utf8');
    if (/\bfrom\s*["']|\bimport\s*\(|\brequire\s*\(/.test(src))
      throw new Error(`${f} still imports something — it must stand alone`);
    if (src.length > MAX_BYTES)
      throw new Error(
        `${f} is ${src.length} bytes (limit ${MAX_BYTES}) — did a dependency get bundled in?`,
      );
    log(`  ${f.padEnd(12)} ${(src.length / 1024).toFixed(1)} kB`);
  }

  // The module, imported in Node: no window → the mock, and the whole API is there.
  const info = console.info;
  console.info = () => {};
  try {
    const mod = await import(`${pathToFileURL(join(out, 'driver.mjs')).href}?v=${Date.now()}`);
    const db = mod.default;
    if (db !== mod.BackendDriver) throw new Error('driver.mjs: default and named export differ');
    for (const k of ['ready', 'firestore', 'rtdb', 'storage', 'kv', 'on', 'serverTime'])
      if (!(k in db)) throw new Error(`driver.mjs: missing ${k}`);
    await db.ready;
    if (db.mock !== true) throw new Error('driver.mjs: expected the mock outside a browser');
    await db.firestore.set('/smoke/a', { n: 1, at: db.serverTime });
    const got = await db.firestore.get('/smoke/a');
    if (got.data?.n !== 1 || !(got.data.at instanceof Date))
      throw new Error('driver.mjs: the mock did not round-trip a document');
  } finally {
    console.info = info;
  }

  // The script: run it against a bare window object and find window.BackendDriver.
  const js = await readFile(join(out, 'driver.js'), 'utf8');
  const fake = { addEventListener() {}, removeEventListener() {}, location: { search: '?mock=1' } };
  fake.parent = fake;
  console.info = () => {};
  try {
    new Function('window', js)(fake);
  } finally {
    console.info = info;
  }
  if (typeof fake.BackendDriver?.firestore?.get !== 'function')
    throw new Error('driver.js did not set window.BackendDriver');

  // The declaration file: flat, and a program that uses it typechecks.
  const dts = await readFile(join(out, 'driver.d.ts'), 'utf8');
  if (/^\s*import\s/m.test(dts)) throw new Error('driver.d.ts has an import — it must be flat');
  await writeFile(join(tmp, 'driver.d.ts'), dts);
  await writeFile(
    join(tmp, 'use.ts'),
    `import db, { BackendDriver, type Doc } from './driver.js';
const same: typeof db = BackendDriver; void same;
export async function go(file: Blob): Promise<Doc<{ n: number }>> {
  await db.ready;
  await db.firestore.set('/a/b', { n: 1, at: db.serverTime }, { merge: true });
  const off = db.firestore.onList<{ n: number }>('/a', { where: [['n', '>', 0]], orderBy: ['n', 'desc'], limit: 5 }, (docs) => void docs[0]?.data?.n);
  off();
  await db.storage.upload('/f.png', file, { contentType: 'image/png' });
  const url: string = await db.storage.url('/f.png'); void url;
  db.on('readonly', (v: boolean) => void v);
  window.BackendDriver.rtdb.on('/x', () => {}, (e) => void e.code);
  const msgs = await db.tickets.thread('ENG-1', { limit: 10, before: 5 });
  void msgs[0]?.agg?.entries[0]?.label;
  db.tickets.onThread('ENG-1', (ms) => void ms.length)();
  db.tickets.onThread('ENG-1', { limit: 5 }, (ms) => void ms[0]?.question?.answer?.by.name)();
  const agg = await db.tickets.aggregates('ENG', { field: 'Cost' });
  void agg.buckets[0]?.tickets['ENG-1']?.total;
  const fileUrl: string = await db.tickets.fileUrl('ENG-1', 'att_1'); void fileUrl;
  return db.firestore.get<{ n: number }>('/a/b');
}
`,
  );
  await writeFile(
    join(tmp, 'tsconfig.json'),
    JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        lib: ['ES2022', 'DOM'],
        module: 'ESNext',
        moduleResolution: 'Bundler',
        strict: true,
        noEmit: true,
        types: [],
      },
      files: ['use.ts'],
    }),
  );
  tsc(['-p', join(tmp, 'tsconfig.json')]);
  log(`  driver.d.ts  typechecks standalone`);
  void version;
}

async function main() {
  if (args.has('--check')) {
    const out = join(here, '.check');
    try {
      await build(out);
      for (const ch of CHANNELS)
        for (const f of FILES) {
          const [a, b] = await Promise.all([
            readFile(join(out, f), 'utf8'),
            readFile(join(STATIC, ch, f), 'utf8').catch(() => null),
          ]);
          if (a !== b)
            throw new Error(
              `frontend/static/backend-driver/${ch}/${f} is stale — run \`pnpm --filter @tm/backend-driver build\``,
            );
        }
      log('backend-driver: staged files are up to date');
    } finally {
      await rm(out, { recursive: true, force: true });
    }
    return;
  }
  log('@tm/backend-driver → frontend/static/backend-driver/{v1,latest}/');
  await build(join(STATIC, 'v1'));
  await mkdir(join(STATIC, 'latest'), { recursive: true });
  for (const f of FILES)
    await writeFile(join(STATIC, 'latest', f), await readFile(join(STATIC, 'v1', f)));
  log('  ✓ staged');
}

await main();
