/**
 * Build the artefacts §M hosts under /lib/v1/ — all five from ONE source.
 *
 *   src/*.ts  ──concat, imports stripped──▶  dist/sdk.ts   (Deno / Bun import this)
 *                                              │
 *                       tsc --emitDeclarationOnly│        esbuild
 *                                              ▼            ▼
 *                                        dist/sdk.d.ts   dist/sdk.js + sdk.min.js
 *                                                           │
 *                                                      npm pack (dist/package/)
 *                                                           ▼
 *                                                dist/tm-sdk-<version>.tgz
 *
 * Concatenating first is what makes the promise in §M cheap to keep: the
 * declaration file is emitted from a file that HAS no imports, so it cannot
 * come out mentioning @tm/shared or zod, and sdk.ts is the very thing that
 * was type-checked and bundled — not a second, drifting copy.
 *
 *   node build.mjs [--no-pack] [--quiet]
 */
import { createRequire } from 'node:module';
import { spawnSync } from 'node:child_process';
import { cp, mkdir, readFile, readdir, rename, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const dist = join(here, 'dist');
const tmp = join(here, '.tmp');
const stage = join(dist, 'package');

const args = new Set(process.argv.slice(2));
const quiet = args.has('--quiet');
const log = (...m) => quiet || console.log(...m);

/**
 * Concatenation order. Every module must come after the ones whose CLASSES
 * and CONSTS it uses at load time (functions hoist, so they are free).
 */
const MODULES = ['types.ts', 'errors.ts', 'http.ts', 'sse.ts', 'zip.ts', 'watch.ts', 'data.ts', 'client.ts', 'work.ts', 'mcp.ts'];

/**
 * Drop the lines that tie a module to its siblings: `import … from './x.js'`
 * (single or multi-line) and `export * from './x.js'`. Anything importing a
 * PACKAGE is a bug — the SDK has no dependencies — so this shouts instead.
 */
function stripLocalImports(source, file) {
  const out = [];
  const lines = source.split('\n');
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const starts = /^\s*(import\b|export\s+(\*|\{|type\s+\{)[^=]*from\b)/.test(line);
    if (!starts) {
      out.push(line);
      continue;
    }
    // Take the whole statement, however many lines it spans.
    let stmt = line;
    while (!/;\s*$/.test(stmt) && i + 1 < lines.length) stmt += '\n' + lines[++i];
    const from = stmt.match(/from\s+'([^']+)'/);
    if (from && !from[1].startsWith('.')) throw new Error(`${file}: the SDK must have no dependencies, but it imports '${from[1]}'`);
    // `import type { X } from './y.js'` and friends: dropped, the file is now one module.
  }
  return out.join('\n');
}

async function concatSource(version) {
  const parts = [];
  for (const file of MODULES) {
    const raw = await readFile(join(here, 'src', file), 'utf8');
    parts.push(`// ───────────────────────── src/${file} ─────────────────────────\n`);
    parts.push(stripLocalImports(raw, `src/${file}`).trim());
    parts.push('\n');
  }
  const banner =
    `/**\n` +
    ` * @tm/sdk ${version} — the TaskManager client, as one dependency-free file.\n` +
    ` *\n` +
    ` * Generated by sdk/build.mjs from sdk/src/*.ts — do not edit. Deno and Bun\n` +
    ` * can import this URL directly and type it natively:\n` +
    ` *\n` +
    ` *   import { createClient } from 'https://taskmanager-example.web.app/lib/v1/sdk.ts'\n` +
    ` */\n\n`;
  // The one value the build stamps in.
  const body = parts.join('\n').replace(/export const VERSION = '[^']*';/, `export const VERSION = '${version}';`);
  if (!body.includes(`export const VERSION = '${version}'`)) throw new Error('build: the VERSION stamp did not apply');
  return banner + body;
}

function run(cmd, argv, opts = {}) {
  const r = spawnSync(cmd, argv, { stdio: quiet ? 'pipe' : 'inherit', encoding: 'utf8', ...opts });
  if (r.status !== 0) {
    if (quiet) process.stderr.write(`${r.stdout ?? ''}${r.stderr ?? ''}`);
    throw new Error(`${cmd} ${argv.join(' ')} → exit ${r.status}`);
  }
  return r;
}

const tscBin = () => join(dirname(require.resolve('typescript/package.json')), 'bin', 'tsc');

async function main() {
  const pkg = JSON.parse(await readFile(join(here, 'package.json'), 'utf8'));
  const { version } = pkg;
  log(`@tm/sdk ${version} → dist/`);

  await rm(dist, { recursive: true, force: true });
  await rm(tmp, { recursive: true, force: true });
  await mkdir(dist, { recursive: true });
  await mkdir(tmp, { recursive: true });

  // 1 ── one file, no imports.
  const single = await concatSource(version);
  await writeFile(join(tmp, 'sdk.ts'), single);
  await writeFile(join(dist, 'sdk.ts'), single);
  log(`  sdk.ts        ${(single.length / 1024).toFixed(1)} kB`);

  // 2 ── the flat declaration file, emitted FROM that file (so it cannot
  //      mention @tm/shared or zod) — and a full typecheck of it on the way.
  // `types: []` keeps @types/node out: the declaration file may only lean on
  // globals every target runtime has (fetch, Response, AbortSignal …).
  await writeFile(
    join(tmp, 'tsconfig.json'),
    JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          lib: ['ES2023', 'DOM'],
          module: 'ESNext',
          moduleResolution: 'Bundler',
          strict: true,
          noUncheckedIndexedAccess: true,
          skipLibCheck: true,
          types: [],
          declaration: true,
          emitDeclarationOnly: true,
          outDir: dist,
        },
        files: ['sdk.ts'],
      },
      null,
      2,
    ),
  );
  run(process.execPath, [tscBin(), '-p', join(tmp, 'tsconfig.json')]);

  // 3 ── the ESM bundle. Deno reads the triple-slash reference; hosting also
  //      sends X-TypeScript-Types (p4-hosting).
  const reference = '/// <reference types="./sdk.d.ts" />';
  const esbuild = await import('esbuild');
  const common = {
    entryPoints: [join(tmp, 'sdk.ts')],
    bundle: true,
    format: 'esm',
    target: 'es2022',
    platform: 'neutral',
    banner: { js: `${reference}\n//! @tm/sdk ${version}` },
    legalComments: 'none',
  };
  await esbuild.build({ ...common, outfile: join(dist, 'sdk.js') });
  await esbuild.build({ ...common, minify: true, outfile: join(dist, 'sdk.min.js') });

  // 4 ── the npm tarball. `types` FIRST in every exports condition, so tsc
  //      and every editor resolve the declaration file from the tarball.
  await mkdir(stage, { recursive: true });
  const tarballPkg = {
    name: pkg.name,
    version,
    description: 'The typed, zero-dependency TaskManager client (REST /v1 + an MCP tool factory).',
    type: 'module',
    types: './sdk.d.ts',
    main: './sdk.js',
    module: './sdk.js',
    exports: {
      '.': { types: './sdk.d.ts', import: './sdk.js', default: './sdk.js' },
      './sdk.ts': './sdk.ts',
      './sdk.min.js': './sdk.min.js',
      './package.json': './package.json',
    },
    files: ['sdk.js', 'sdk.min.js', 'sdk.d.ts', 'sdk.ts', 'README.md'],
    sideEffects: false,
    engines: { node: '>=20' },
    license: 'UNLICENSED',
  };
  await writeFile(join(stage, 'package.json'), JSON.stringify(tarballPkg, null, 2) + '\n');
  for (const f of ['sdk.js', 'sdk.min.js', 'sdk.d.ts', 'sdk.ts']) await cp(join(dist, f), join(stage, f));
  await cp(join(here, 'README.md'), join(stage, 'README.md'));

  if (!args.has('--no-pack')) {
    run('npm', ['pack', '--silent', '--pack-destination', dist], { cwd: stage });
    // `@tm/sdk` packs as tm-sdk-<version>.tgz, which is the name §M hosts.
    const tgz = (await readdir(dist)).find((f) => f.endsWith('.tgz'));
    if (!tgz) throw new Error('build: npm pack produced no tarball');
    const want = `tm-sdk-${version}.tgz`;
    if (tgz !== want) await rename(join(dist, tgz), join(dist, want));
    // §M hosts both names: the pinned one and a moving `tm-sdk.tgz`.
    await cp(join(dist, want), join(dist, 'tm-sdk.tgz'));
    log(`  ${want} (+ tm-sdk.tgz)`);
  }

  await smoke(version);
  await rm(tmp, { recursive: true, force: true });
  log('  ✓ every artefact imported and checked');
}

/** Import each artefact and look at it, so a broken build never ships. */
async function smoke(version) {
  const dts = await readFile(join(dist, 'sdk.d.ts'), 'utf8');
  const leak = dts.match(/from\s+'(@tm\/shared|zod|[^']*\/shared[^']*)'/);
  if (leak) throw new Error(`sdk.d.ts still imports ${leak[1]} — it must be flat`);
  if (/^\s*import\s/m.test(dts)) throw new Error('sdk.d.ts has an import statement — it must be flat');
  for (const name of ['createClient', 'TmError', 'mcpTools', 'registerTools', 'VERSION'])
    if (!dts.includes(name)) throw new Error(`sdk.d.ts is missing ${name}`);

  const ts = await readFile(join(dist, 'sdk.ts'), 'utf8');
  if (/^\s*import\s/m.test(ts)) throw new Error('sdk.ts has an import statement — it must stand alone');

  const js = await readFile(join(dist, 'sdk.js'), 'utf8');
  if (!js.startsWith('/// <reference types="./sdk.d.ts" />'))
    throw new Error('sdk.js must start with the triple-slash reference (Deno and Bun read it)');

  for (const file of ['sdk.js', 'sdk.min.js']) {
    const mod = await import(pathToFileURL(join(dist, file)).href);
    for (const name of ['createClient', 'TmError', 'mcpTools', 'registerTools', 'isTmError', 'VERSION'])
      if (!(name in mod)) throw new Error(`${file} does not export ${name}`);
    if (mod.VERSION !== version) throw new Error(`${file} says version ${mod.VERSION}, expected ${version}`);
    const tm = mod.createClient({ token: 'tm_live_smoke', baseUrl: 'http://127.0.0.1:1/v1', fetch: async () => new Response('{}') });
    if (tm.version !== version || !tm.baseUrl.endsWith('/v1')) throw new Error(`${file}: createClient did not come up`);
    const tools = await mod.mcpTools(tm, { scopes: ['tickets:read'] });
    if (!tools.some((t) => t.name === 'get_ticket')) throw new Error(`${file}: mcpTools returned nothing usable`);
  }

  if (!args.has('--no-pack') && !existsSync(join(dist, `tm-sdk-${version}.tgz`))) throw new Error('the tarball is missing');
}

await main();
